CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  age TINYINT(3) UNSIGNED NOT NULL,
  country VARCHAR(255) NOT NULL,
  social_media_url VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);